apiVersion: v1
kind: Service
metadata:
  name: geth-devnet
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: geth-devnet
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.rpc }}
      nodePort: {{ .Values.service.nodePort.rpc }}
      {{- end }}
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.ws }}
      nodePort: {{ .Values.service.nodePort.ws }}
      {{- end }}
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.p2p }}
      nodePort: {{ .Values.service.nodePort.p2p }}
      {{- end }}
    - name: metrics
      port: 6060
      targetPort: metrics
      protocol: TCP
